### ISSUE TITLE
NullPointerException thrown on showMessage [Android]

### ISSUE THREAD

**Issue by PieterAelse** [ice-j/Plugin.XSnack#3]
When I try to show a XSnackbar I get a NullPointerException. I'm running on Android, can't test on iOS because I'm on Windows.

Details:

> {System.NullReferenceException: Object reference not set to an instance of an object.
>   at Plugin.XSnack.XSnackImplementation.DisplayMessage (System.String message, System.Int32 duration, System.String actionText, System.Windows.Input.ICommand actionCommand) [0x00021] in <7951a697453f4916b4eea63c683cfeba>:0 
>   at Plugin.XSnack.XSnackImplementation.ShowMessage (System.String message, System.Int32 duration, System.String actionText, System.Windows.Input.ICommand actionCommand) [0x00000] in <7951a697453f4916b4eea63c683cfeba>:0 
>   at App1.MainPage.ShowMessage (System.String text) [0x00019] in \MainPage.xaml.cs:48 }

Code:
```
if (Plugin.XSnack.CrossXSnack.IsSupported && Plugin.XSnack.CrossXSnack.Current != null)
{
    try
    {
        Plugin.XSnack.CrossXSnack.Current.ShowMessage(text);
    }
    catch (Exception e) {
        Console.WriteLine(e);
    }
}
```

**Comment by ice-j** [comment]
Hi @PieterAelse, can you provide more info such as Android version, Xamarin.Forms version, device info please?

**Comment by PieterAelse** [comment]
Sure @ice-j ,

Xamarin Forms version: v3.5.0.129452 (latest)
Plugin version: v1.0.17 (latest?)
Android version: 9
Device: Samsung Galaxy S9

I also tested on a virtual Android 8.1 device, same issue.

**Comment by ice-j** [comment]
Hi @PieterAelse I've just debugged the error you're mentioning and it looks like you're missing the `CrossCurrentActivity.Current.Init(Application);` initialization in your MainActivity. 

You can check out the sample project that's within the repo for more info.

Sorry for late response.

I've confirmed this on OnePlus 6T (Android 9.0) and Samsung Galaxy S8 (Android 8.0).

**Comment by PieterAelse** [comment]
@ice-j After that it worked, thanks for pointing it out!

But is it me or is that nowhere to be found in the Readme or wiki pages?...

**Comment by ice-j** [comment]
It's not you, I'll put it in the readme :) Thanks for noticing :)
